### ISSUE TITLE
Audio Output compatibility

### ISSUE THREAD

**Issue by Felix14-v2** [Gaider10/SilentBackground#1]
Both mods use the same button location:
![image](https://user-images.githubusercontent.com/75726196/136098201-c547141c-3829-404a-8520-de9976e3dcc0.png)

Perhaps this is a problem from the [Audio Output](https://www.curseforge.com/minecraft/mc-mods/audio-output/) side, I will try to contact its author as well.

**Comment by Gaider10** [comment]
Fixed in 1.0.1
