### ISSUE TITLE
1.19.1 - Crashes Game When Opening Music and Sounds Settings

### ISSUE THREAD

**Issue by LOLboy199** [Gaider10/SilentBackground#3]
Mod still works in 1.19.1, and still the best option that I know of for adjusting specific sound levels when the screen is unfocused. 
Obviously the mod is far out of date because I don't think the owner still does anything with it, so it crashes when opening the music and sound settings, the sound levels are still configurable by editing the .txt file, but it would be nice to access all the MC menus at any time lol

I have no clue how to 'fork' or 'port' to newer versions or really anything with coding, but if someone else does or can explain to me what I need to do in the code to make this work, then any help would be appreciated.

**Comment by zwamdurkel** [comment]
https://github.com/zwamdurkel/SilentBackground/releases/download/Release/SilentBackground-1.0.2-1.19.x.jar

This version should fix your issue. I manually updated the mod and have created a pull request #4

**Comment by LOLboy199** [comment]
Bless you. That worked perfectly. Works in 1.19.2 and with all my other mods.
